---
title: "PM-566 Midterm"
author: "Chris Hanson"
date: "10/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(httr)
```

From: 
https://www.who.int/data/gho/info/gho-odata-api
and
https://uscbiostats.github.io/PM566/slides/07-apis-regex/slides.html#30


Retrieving the list of available dimension codes
```{r}
dimquery <- GET(
  url = "https://ghoapi.azureedge.net/api/Dimension/"
)

dimquery$status_code

dimensions <- content(dimquery, "parsed")
dimensions <- lapply(dimensions$value, function(a){
  data.frame(
  CODE    = a$Code,
  TITLE   = a$Title
  )
})
dimensions <- do.call(rbind, dimensions)
head(dimensions)
```

Retrieving a list of available values for a specific dimension
```{r}
valuesquery <- GET(
  url = "https://ghoapi.azureedge.net/api/DIMENSION/COUNTRY/DimensionValues/"
)

valuesquery$status_code

dimensionvalues <- content(valuesquery, "parsed")

for(i in 1:length(dimensionvalues$value)) {
  is.na(dimensionvalues$value[[i]]) <- dimensionvalues$value[[i]] == "NULL"
}

dimensionvalues <- lapply(dimensionvalues$value, function(b){
  data.frame(
    Code            = b$Code,
    Title           = b$Title,
    Dimension       = b$Dimension,
    ParentDimension = b$ParentDimension,
    ParentCode      = b$ParentCode,
    ParentTitle     = b$ParentTitle
  )
})
dimensionvalues <- do.call(rbind, dimensionvalues)
head(dimensionvalues)
```


    Code            = b$Code,
    Title           = b$Title,
    Dimension       = b$Dimension,
    ParentDimension = b$ParentDimension,
    ParentCode      = b$ParentCode,
    ParentTitle     = b$ParentTitle
