---
title: "PM-566 Midterm"
author: "Chris Hanson"
date: "10/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(httr)
library(xml2)
library(data.table)
library(plyr)
```

From: 
https://www.who.int/data/gho/info/gho-odata-api
and
https://uscbiostats.github.io/PM566/slides/07-apis-regex/slides.html#30


Retrieving the list of available dimension codes. This is a learning example.
```{r first-example}
# Retrieving dimensions
dimquery <- GET(
  url = "https://ghoapi.azureedge.net/api/Dimension"
)

# Checking if the website is active
dimquery$status_code

# Processing data
dimensions <- content(dimquery)

# The data is in the second element of the "dimensions" list.
# This really makes a nice data frame.
dimensions <- do.call(rbind, dimensions[[2]])
# dimensions <- rbindlist(dimensions[[2]]) #equivalently

# So nice, check it out!
head(dimensions)
```

Retrieving a list of available values for a specific dimension
```{r second-example}
# This seems to just give a list of all countries.
# Same process as first example.

valuesquery <- GET(
  url = "https://ghoapi.azureedge.net/api/DIMENSION/COUNTRY/DimensionValues"
)

valuesquery$status_code

dimvals <- content(valuesquery)

# The code provided by ggvy makes the below unnecessary

#for(i in 1:length(dimvals$value)) {
#  is.na(dimvals$value[[i]]) <- dimvals$value[[i]] == "NULL"
#}

# Here's why the below is unnecessary:

#dimvals <- lapply(dimvals$value, function(b){
#  data.frame(
#    Code            = b$Code,
#    Title           = b$Title,
#    Dimension       = b$Dimension,
#    ParentDimension = b$ParentDimension,
#    ParentCode      = b$ParentCode,
#    ParentTitle     = b$ParentTitle
#  )
#})

# Instead we jump straight into
#dimvals <- do.call(rbind, dimvals[[2]]) #This way makes it NULL, his makes it NA:
dimvals <- rbindlist(dimvals[[2]])

head(dimvals)
```

Retrieving a list of available indicators
```{r}
# This results in a list of all indicators! Legit useful.

# Actually my way did work but hell it was inelegant, let's change it:
indicatorsquery <- GET(
  url = "https://ghoapi.azureedge.net/api/Indicator/"
)

indicatorsquery$status_code

indicators <- content(indicatorsquery)

#indicators <- lapply(indicators$value, function(c){
#  data.frame(
#    IndicatorCode  = c$IndicatorCode,
#    IndicatorName  = c$IndicatorName,
#    Language       = c$Language
#  )
#})

# The ggvy way
indicators <- rbindlist(indicators[[2]])

head(indicators)
```

Retrieving indicator (malaria example) data
```{r malaria-example}
malariaquery <- GET(
  url = "https://ghoapi.azureedge.net/api/MALARIA002/"
)

malariaquery$status_code

malaria <- content(malariaquery)

malaria <- rbindlist(malaria[[2]])

library(ggplot2)
ggplot(subset(malaria,SpatialDim %in% c("AFG")), aes(x = TimeDim, y = NumericValue)) +
  geom_line() +
  labs(
    x = "Year",
    y = "Rate"
  )

```


```{r medical-doctors}
docsquery <- GET(
  url = "https://ghoapi.azureedge.net/api/imr"
)

docsquery$status_code

docs <- content(docsquery)

docs <- rbindlist(docs[[2]])
```

