---
title: "pm566midtermWB"
author: "Chris Hanson"
date: "10/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(httr)
library(xml2)
library(data.table)
```

WORLD BANK

Retrieving from The World Bank API
https://datahelpdesk.worldbank.org/knowledgebase/articles/898599-indicator-api-queries
```{r}
WBindicatorsquery <- GET(
  url = "http://api.worldbank.org/v2/indicator/NY.GDP.MKTP.CD?source=11"
)

WBindicatorsquery$status_code

WBI <- content(WBindicatorsquery, "text")

WBI2 <- read_xml(WBI)

WBI3 <- as_list(WBI2)



WBindicators3 <- lapply(WBindicators$data$data, function(d){
  data.frame(
    Indicator = d$indicator[[1]],
    Country   = d$country[[1]]
  )
})

#Below doesn't work yet
#WBindicators3 <- do.call(rbind, WBindicators)
```

indicators <- lapply(indicators$value, function(c){
  data.frame(
    IndicatorCode  = c$IndicatorCode,
    IndicatorName  = c$IndicatorName,
    Language       = c$Language
  )
})
indicators <- do.call(rbind, indicators)
head(dimensionvalues)
